### ISSUE TITLE
Validating dynamically added fields

### ISSUE THREAD

**Issue by peimn** [vuelidate/vuelidate#1038]
**Describe the bug**
I'm trying to add dynamic fields to a form and validate them.
The code below adds validation to each field, but whenever I add a field to a form, the validation validates the form and shows me the error before it is submitted. Additionally, when I use i18n, the error shows just `validation.undefined`

**Reproduction URL**
https://playcode.io/882096/

* In the meantime, code sandbox does not work due to errors.

**Comment by dobromir-hristov** [comment]
The added field is considered invalid, because the new simplified `$eachHelper` relies on the `$dirty` property of the container property, in your case `items`. 

If you want more advanced collection validation, use either the EachComponent or separate components.

https://vuelidate-next.netlify.app/advanced_usage.html#validating-collections
