### ISSUE TITLE
Passing Vuelidate instance as modal data makes it undefined

### ISSUE THREAD

**Issue by zortext** [vuelidate/vuelidate#1041]
**Describe the bug**
I have a Vuelidate instance in a form component. Another parent component includes it and needs to access it's validator instance through a 2-way model binding.

The weird problem is if I set Vuelidate instance in the child for model value, then it set as undefined in the parent component. Bu if a encapsulate it in an object like {validator} then data pass to parent successfully. 

**Reproduction URL**
Logs undefined
https://codesandbox.io/s/zor-tt-hd63ysfk-ewgqnt

Logs as expected
https://codesandbox.io/s/zor-tt-hd63ysfk-forked-zu6m4q

**Expected behavior**
2-way binding value should pass the Vuelidate instance to parent.

 
Also on https://stackoverflow.com/questions/71910389/passing-vuelidate-instance-as-modal-data-makes-it-undefined

**Comment by dobromir-hristov** [comment]
Instead of passing the validator as a prop back to a component, you can rely on our automatic parent-child internal communication.

If a component has `useVuelidate` called, it will collect all of it's children validation instances. They are not only accessible in the parent, but also augment it's `$error` and `$errors` properties, so you can use them as you wish.

Here is an example, using the scopes docs.

https://vuelidate-next.netlify.app/advanced_usage.html#validation-scopes
