### ISSUE TITLE
Will there be a production version of vuelidate ? (current is alpha version)

### ISSUE THREAD

**Issue by hkk2018** [vuelidate/vuelidate#1078]
I was asked to make sure all project dependencies are stable version, but I found vuelidate has been alpha version since 3 years ago.
Would there be a production version of vuelidate? Any schedule for it?
I will appreciate your help with this situation.

**Comment by dobromir-hristov** [comment]
Hey there. It has been mostly stable, but I never changed it beyond the alpha, because I was not sure if we are ready and satisfied with the API.

I think users are using it and are mostly happy.

The docs need a bit more love, but overall I think we can bump the version to stable.

Going on vacation today, will check when I get back

**Comment by hkk2018** [comment]
Thanks for your reply.

As a user, I feel good with the API so far.

Hope to see the stable version launch soon!

**Comment by hkk2018** [comment]
Hi, @dobromir-hristov, how is the project going?

**Comment by ebisbe** [comment]
There was a discussion on reddit about wether it is production ready or not as it is in `alpha` state. If the api is stable and has been it should be at least be able to be in beta. The docs can be improved but that's aside from the core. I'm satisfied with the api. 

Give it some love and move it to stable.

**Comment by thedamon** [comment]
Honestly this needs to happen soon. We want to upgrade our project to Vue 3 but having an alpha dependency in our npm modules is not going to fly. Wish you could get the support of the core Vue team for this project or something. Major deps like this without enough resources to be prod ready in Vue 3 is keeping the ecosystem back in a big way.

**Comment by shayneo** [comment]
Not trying to pile on as the work on this project is certainly appreciated. That said, it does seem like the right move from a community standpoint to move to a GA (2.x) release. From this comment https://github.com/vuelidate/vuelidate/issues/1078#issuecomment-1171959960 it reads as though there are still some questions from the core team about the API.

If that's the case perhaps there could be some open dialog about how to address those questions/concerns. Such as:
- A public list of issues required for 2.x GA
- RFCs for API change proposals for 2.x

The other approach is releasing a 2.x GA version and then incorporating breaking changes later on under a new major version (3.x, etc)

It would be sad to see this project get forked/unused because of the alpha label, when there is a chance that the alpha label isn't currently needed.

**Comment by dobromir-hristov** [comment]
Alright, 2.0 is released. I will change the bundler of the package, but thats a minor internals change, so should not change the API what so ever.
