### ISSUE TITLE
Error Messages Helper Function

### ISSUE THREAD

**Issue by Austio** [vuelidate/vuelidate#149]
Hello,

What do you think about a function like `$errors` similar to $flattenParams that collects a generic list/dictionary of errors from vuelidate parameters.

This is specific to my implementation but helper would be something slightly more generic than this that doesn't assume we want the last param in the form path..

```
          const params = this.$v.form.$flattenParams();
          const invalidParams = params.reduce((acc, param) => {
            const path = param.path.join('.');
            const validation = param.name;

            const isValid = _get(this, `$v.form[${path}][${validation}]`, true);
            if (!isValid) {
              const paramNameLocation = param.path.length - 1;

              acc.push({ [param.path[paramNameLocation]]: param.name });
            }
            return acc;
          }, []);

         return _isEmpty(invalidParams) ? false : invalidParams;

// Returns a list like this
[
  { 
    "city_id": "required"
  }
]
```

Usage would be something like this
```
submitForm() {
  if ($v.form.$errors) {
    // Handle stuff that is errored from the form 
  }
}

or in template

<p v-for="(error, index) in $v.form.$errors">
  {{ error | myErrorFormatter }}
</p> 
```

I have read through #3 and a couple other issues with discussion on passing in custom messages.  I think this is different because it is a helper for collecting data that can be formatted however someone would want.

**Comment by Frizi** [comment]
Thanks for doing the hard part of figuring things out here :)

First point, i think that `$errors` can get pretty easily confused with `$error` prop.
Also, you don't have to base your implementation on `$flattenParams`really (and `_get`, that looks fragile). But it does surely work as a good proof of concept, more thoughtful implementation can be easily done later. I'd like to first think about desired API instead of focusing on implementation.

By my personal taste, I'd construct the template part more around custom components, like i previously suggested doing in https://github.com/monterail/vuelidate/issues/3#issuecomment-276457558
But that certainly isn't the only way to do it. What i'm missing in your proposal is the distinction between *local errors* and *nested errors*. Currently, local errors are just a collection props on your validation object, and for global ones you really have to traverse the tree.  Also there is no concept of order in validators currently, you kinda just grab them in random one (which might often be just fine).

Going back, flattenParams` was meant to make the second case easier, while still providing you enough information to filter out only the things you are interested in. It also gave you only the "metadata" and set of paths, with the idea that you still might easily get the actual field state using it. So it kinda avoided the problem in the first place, while introducing a second one - not being terribly useful.

What if we make it more useful? Currently `$params` are also derived from validation function run, so we are not gaining anything by exposing `$params` only. Adding a `invalid` field would make a lot of sense here.

Even that might actually work:
```html
<p v-for="errorParam in $v.form.$flattenParams()" v-if="errorParam.invalid">
  {{ errorParam | myErrorFormatter }}
</p> 
```

It's still missing the depth and sorting though. And to be honest, the name doesn't fit anymore.

What if instead we could do something like that 
```html
<p v-for="(error, index) in $v.form.$format({onlyErrors: true, recursive: false, orderWith: myCustomSorter})">
  {{ error | myErrorFormatter }}
</p> 
```

**Comment by Austio** [comment]
Agreed on the `$errors` name being confusing.
 
Great ideas, it seems to me like the first way would be easiest, could even combine the ideas so that $flattenParams takes an argument $flattenParams({ onlyErrors: true,... }).  

I think the orderWith would be better on the client side but there may be something i'm not thinking of.

Quick psuedo stab at thought, could be way off on it :man_shrugging: 

```
  $flattenParams ({ onlyErrors: false, recursive: true }) {
    const proxy = this.proxy
    let params = []
    for (const key in this.$params) {
      if (recursive && this.isNested(key)) {
        const childParams = proxy[key].$flattenParams(arguments[0])
        for (let j = 0; j < childParams.length; j++) {
          childParams[j].path.unshift(key)
        }
        params = params.concat(childParams)
      } else {
        if (onlyErrors && PARAM_IS_VALID) {
          return
        }
        params.push({ path: [], name: key, params: this.$params[key] })
      }
    }
    return params
  }
```

**Comment by SirLamer** [comment]
Here is my implementation. In this context, I have implemented Vue components for each type of form field (input elements), and one of the properties "validation" excepts the relevant Vuelidate validation branch associated with the input field. This communicates to the component if it is invalid, and is used to inform its display state. This includes providing a message on each validation error under the form field.

My implementation is based on the build-in values and methods all having a dollar sign leading them, so I just filter for the objects which don't have a dollar sign.

```js
computed: {
        getValidationErrors() {
            if (!(this.validation && this.validation.$error)) {
                return [];
            }

            const buffer = [];

            Object.keys(this.validation).forEach((key) => {
                if (!key.startsWith('$') && typeof this.validation[key] === 'boolean' && !this.validation[key]) {
                    buffer.push({
                        type: key,
                        message: this.$t(
                            'vuelidate.' + key,
                            Object.assign({attribute: this.displayTitle || $t('ui.field')}, this.validation.$params[key])
                        )
                    });
                }
            });

            return buffer;
        }
}
```

**Comment by petridw** [comment]
I wrote a mixin for this purpose a while ago which gives your component a computed array `$allErrors` containing all of the invalid validations inside the $v object in the form:
```
{
  key: "fieldName",
  error: "errorType",
  params: { /* error params object */}
}
```
At that point it's pretty straightforward to write a component which can consume that array and spit out a nice error list, localized however you want.

The implementation could probably get cleaned up but it gets the job done. It just assumes anything inside $v that doesn't start with $ is a validation.
```
"use strict";

export default {
  name: "vuelidate-helper",

  computed: {
    $allErrors() {
      return this.$getDeepErrors({ $v: this.$v }, "$v");
    },
  },

  methods: {
    $getDeepErrors(outerObj, outerKey) {
      const obj = outerObj[outerKey];
      return Object.keys(obj).reduce((acc, key) => {
        if (key.charAt(0) === "$" && key !== "$store" && key !== "$each") return acc;
        if (typeof obj[key] === "object") {
          return acc.concat(this.$getDeepErrors(obj, key));
        }
        if (!obj[key]) {
          acc.push({
            key: outerKey,
            error: key,
            params: obj.$params[key],
          });
        }
        return acc;
      }, []);
    },
    $getShallowErrors(obj) {
      return Object.keys(obj).filter(key => key.charAt(0) !== "$").filter(key => !obj[key]);
    },
  },

  created() {
    if (!this.$v) {
      throw new Error(
        `vuelidate-helper is meant to be used in a component with vuelidate validations. ${this.name} does not have a $v validation object.`
      );
    }
  },
};
```

It also adds a method `$getShallowErrors` which can be used to get an array of a single level of errors.

**Comment by sekys** [comment]
Hello guys,

thank you for your examples. Based on it i build similar solution. Also it is integrated with a **vue-i18n**.

```
model.computed.emailError = function () {
	return this.getValidationErrors(this.$v, "email");
};
model.computed.passwordError = function () {
	return this.getValidationErrors(this.$v, "password");
};
model.methods.getValidationErrors = function (validator, attr) {
	if (!validator.$invalid ) {
		return "";
	}

	var data = validator[attr];
	if(data.$dirty == false) {
		return "";
	}
	for (var key in data) {
		var value = data[key];
		// typeof value === 'boolean'
		if (!key.startsWith('$') && value === false) {
			var context = data.$params[key];
			var msg = window.i18n.t('vuelidate.' + key, context);
			return msg;
		}
	}
	return "";
};
```

Message bundle:
```
window.messages = window.messages || {};
window.messages.sk = window.messages.sk || {};
var sk = window.messages.sk;

sk.vuelidate = sk.vuelidate || {};
sk.vuelidate.required =  "toto pole je povinne";
sk.vuelidate.minLength =  "minimalna dlzka pola je {min}";
sk.vuelidate.email =  "Zadajte prosim email v spravnom tvare";
```

Then I use `emailError` to print first error, if it exist.

**Comment by dobromir-hristov** [comment]
I did my own version of this. Someone might check it out and tell me their thoughts? 
https://dobromir-hristov.github.io/vuelidate-error-extractor/

**Comment by adrielairaldo** [comment]
Hi guys, I got to this thread because I'm migrating to Vue from KO.

Like you, I'm interested in configuring particular error messages, and maintaining a clear link between error messages and model elements, and keeping message generation logic out of view elements.

I wanted to share with you (without hateful intentions) the way in which I achieved the above, using KO:

```javascript
    var viewModel = {
        razonSocial: ko.observable()
            .extend({required: { params: true, message: 'Ingrese Razón Social.' }})
            .extend({maxLength: { params: 150, message: 'Máxima longitud alcanzada.' }}),
        domicilio: ko.observable()
            .extend({maxLength: { params: 150, message: 'Máxima longitud alcanzada.' }}),
        telefono: ko.observable()
            .extend({pattern: { params: '^[0-9() +-.]+$', message: 'El número de teléfono ingresado no es válido.' }})
            .extend({maxLength: { params: 100, message: 'Máxima longitud alcanzada.' }}),
        email: ko.observable()
            .extend({email: { params: true, message: 'El formato del email ingresado no es válido.' }})
            .extend({maxLength: { params: 254, message: 'Máxima longitud alcanzada.' }}),
        rubros: ko.observableArray()
            .extend({minArrayLength: {params: {minLength: 1}, message: 'Debe seleccionar al menos 1 rubro.'}})
    };
```

In the code above, you can see how for each element of the viewModel I can add particular validations using 'extend'. At the same time, for each observable-validation pair I can configure a particular error message.

An interesting and very useful aspect, is to define the way in which the view will behave generically for each error. You can define constants as follows:

```javascript
        errorElementClass: 'has-error',
        errorMessageClass: 'help-block',
        decorateInputElement: true
```

The code above was meant to be used with Bootstrap; It achieves that when an error exists, the 'form-group' div adds the 'has-error' class, and also adds a 'span' with class 'help-block'.

I hope my contribution is useful, my comments are well intentioned. I'll be aware.

Knockout: http://knockoutjs.com/
Knockout Validation: https://github.com/Knockout-Contrib/Knockout-Validation

**Comment by adrielairaldo** [comment]
@dobromir-hristov I am seeing your contribution, excellent work! I will comment as soon as possible.

**Comment by bk-dev** [comment]
@Frizi  Any movement on this? I think it would be beneficial to support a global default error message for a given validator, as well as the ability to override it locally. This message would be retrievable on the relevant nested object in $v (e.g. $v.record.field1.$msg).

Thanks for publishing this library for all of us to use!

**Comment by Frizi** [comment]
@bk-dev The syntax you propose is impossible. You can't define fields on primitive values. What's currently supported is `$v.record.$params.field1`, and you can use this object to derive your own message. Just write a mapping function for that.

**Comment by dobromir-hristov** [comment]
@bk-dev Use the [vuelidate-error-extractor](https://dobromir-hristov.github.io/vuelidate-error-extractor/) it pretty much does this so you dont have to care about it :)

**Comment by dobromir-hristov** [comment]
### I am closing this for now. 

We will rethink the API in the upcoming version and add error extraction helpers. For now use the [vuelidate-error-extractor](https://github.com/dobromir-hristov/vuelidate-error-extractor). If you have issues, post them there for now.
