### ISSUE TITLE
Using vuelidate to use 1 object variable genre with 3 fields

### ISSUE THREAD

**Issue by sergeynilov** [vuelidate/vuelidate#270]
Hello,
In my Laravel 5.5/vue.js2.5/ vuetify,1.0.8 application I use vuelidate ( https://github.com/monterail/vuelidate ) library and I found a problem, as 
having editor of object ( genre ) which has several fields, I prefer define 1 variable, as :

```
...
        data: () => ({
            genre: {
                name: '',
                description: '',
                published: false,
            },
```

and define the input for “name” field:
```
		<v-text-field
				label="Name"
				v-model="genre.name"
				:error-messages="nameErrors"
				:counter="10"
				@input="$v.name.$touch()"
				@blur="$v.name.$touch()"
				required
		></v-text-field>
```

But with syntax above validation “on fly” does not work

I made fiddle https://jsfiddle.net/b5v4faqf/1743/ 
It raise an error now, but I want to know if is there is a way to use 1 object variable genre with 3 fields?

If yes, which valid syntax must be for this?

If this the valid branch for my question ?

Thanks !

**Comment by DinsmoreDesign** [comment]
Trying to decipher your question, but I'm pretty sure you want to nest a model within another property?

Your original fiddle doesn't work correctly because you're passing "text" to the validator object. "Text" doesn't exist in your data, so nothing validates.

Without knowing what your component there actually looks like, I just rebuilt it as a simple label/input like this, which works:

https://jsfiddle.net/k576wgha/

However, if you're wanting to nest "genre" objects inside the parent, you'll need to make use of the $each method, as shown here:

https://jsfiddle.net/gve1js47/
