### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'this.getRef(t).proxy') with vue@2.5.17-beta.0

### ISSUE THREAD

**Issue by OCJvanDijk** [vuelidate/vuelidate#319]
There might be more compatibility problems with Vue 2.5.17 and it's designated beta, but I wanted to share this error. I tested it in Vue 2.5.16 and it works fine.

[JSFiddle reproduction](https://jsfiddle.net/Gemvox/ab9sn7d5/15/)

Click the buttons in order and you'll get the error.
Skip any button and you won't get the error.
Note that I commented out the `<pre>{{ $v }}</pre>` because when it is touched the example won't work anymore (You'll still get the error but it requires less button clicks)

P.S. Another way to get the error seems to be check -> replace -> add

P.P.S. As I understand it, 2.5.17 is beta not because they might still change it, but because there might be compatibility issues like this.

**Comment by OCJvanDijk** [comment]
vuejs/vue#7960 might be related.
Maybe it's beta for a reason after all 😁

**Comment by SirLamer** [comment]
Vue 2.5.17-beta.0 makes a very big change in an attempt to correct a very big performance problem with the v2 branch up to 2.5.16 inclusive.

Basically, the reactivity function of vuejs was undermined and a re-compute action of a computed property in a parent component which did not change the output value would nonetheless trigger dependant children components to wastefully re-render themselves. This effectively was making the entire page re-render without any value in doing so. It was quite wasteful and limited the upward maximum complexity of a Vue-based application since performance optimization could not be managed by breaking elements in to separate patterned components as is the whole intent of Vue.js.

It's labeled as "beta" because it was known that this change could break things and they didn't want an automatic package update to unexpectedly break applications. In truth the new functionality is much more efficient and other applications like Vuelidate need to adjust to accommodate this. They were really getting away with not causing an error before because Vue itself was not working correctly.

**Comment by SirLamer** [comment]
Looks like somebody submitted a PR to Vue to fix this, awaiting merge.

https://github.com/vuejs/vue/pull/7980

**Comment by dobromir-hristov** [comment]
Looks like they fixed it on Vue itself. If it persists we can re-open.
