### ISSUE TITLE
Laravel validation - show the error messages

### ISSUE THREAD

**Issue by ecmattos** [vuelidate/vuelidate#352]
I'm starting in the VueJS world and I really loved this package!
I would like to use this package with Laravel and Quasar (Vue, vuex, axios and vuelidate).
I'm making APIs available for query, inclusion, editing, and deletion of records but I want to perform server-side checks (Laravel validations).
I'd like some help on how to show error messages from Laravel's validations.
Can anybody help me ?

**Comment by phong-et** [comment]
This validation don't support object message as validation of jQuery 
But it is support customize show/hide error message by a component ( in their document http://prntscr.com/kowun3 ). i think it's more flexible for vue. Because vue component is not a pure html, so generating automatic "<span>" message error like jQuery will occur some issues don't expect
