### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by wuxiushang** [vuelidate/vuelidate#385]

**Comment by UltraCakeBakery** [comment]
Keep up the great work @wuxiushang proud of you

**Comment by kosanr1** [comment]
Please provide description for this issue

**Comment by donutDonut123** [comment]
I got same problem:
```
[Vue warn]: Error in render: "RangeError: Maximum call stack size exceeded"

found in

---> <AccountRegistration> at src/components/account-registration/account-registration.vue
       <MyForms> at src/MyForms.vue
         <Root>
```
And it's because inside few form inputs, i.e.:
```
<div class="form-group input-field">
    <label for="login">Login*</label>
    <input id="login" type="text" placeholder="Your login" v-model="$v.formValues.login.$model" v-bind:class="{'is-invalid': $v.formValues.login.$error}">
    <span v-if="!$v.formValues.login.required" class="invalid-feedback">Login is required</span>
    <span v-if="!$v.formValues.login.between" class="invalid-feedback">Login should be between 2 and 100 characters long</span>
</div>
```
inside `v-bind:class` instead of `{'is-invalid': (!$v.formValues.login.between || !$v.formValues.login.required)}` I used `$v.formValues.login.$error`.

That call to .$error causes this maximum call stack error.

When returned to using longer boolean checks, with `||`, stack error stop showing...
Using .$error is convenient, but causes errors.

Why is that?
