### ISSUE TITLE
Proposition : $errors as array of non passing validators

### ISSUE THREAD

**Issue by y-nk** [vuelidate/vuelidate#419]
Hi !

I'd like to know if it would be possible to add an array of validator's names (`$errors`) for each non passing validator of each value : 

**How would it look like :**

```js
// here nothing change
validations: {
  foo: { required, minLength: minLength(4) }
}

// ... somewhere later (or by user input)

foo = ''
console.log($v.foo.$errors) // ['required, 'minLength']
foo = 'foo'
console.log($v.foo.$errors) // ['minLength']
foo = 'foobar'
console.log($v.foo.$errors) // []
```

**This would enable :** 

- validator priority (defined by key order)
- possibility to list all the errors in template : `<strong v-for="error in $v.foo.$errors">{{ error }}</strong>`
- possibility to use validator key as reference for i18n : `<strong v-if="$v.foo.$errors.length">{{ $t($v.foo.$errors[0]) }}</strong>`

**How hard would that be :** 

Probably not much more than a new validation getter such as : 

```
  $errors() {
    const proxy = this.proxy
    return this.ruleKeys.filter((rule) => !proxy[rule])
  },
```

<br>

If this feature is not already coded, and you're willing to accept it but have no time to code it, let me know and i'll submit a PR.

Thanks for reading !

**Comment by thedamon** [comment]
I was looking for something similar in order to put "We found X errors with your submission" (and then possibly list and link to each field that has an error at the top of a form. This is a really useful thing to do for accessibility. I realized there is no straightforward way to access which fields have errors (complicated by nesting of course). This looks like a pretty good and flexible approach to enable that and other things.

**Comment by y-nk** [comment]
@NataliaTepluhina thanks for adding the feature request tag. Does that mean I should submit a PR or are you guys still considering it?

**Comment by luckylooke** [comment]
Related issues:
https://github.com/vuelidate/vuelidate/issues/149
https://github.com/vuelidate/vuelidate/issues/339
https://github.com/vuelidate/vuelidate/issues/325

All ends up with advice:
Use the https://github.com/dobromir-hristov/vuelidate-error-extractor for now.

**Comment by thedamon** [comment]
The vuelidate-error-extractor doesn't seem to do what this suggests. It seems to be entirely oriented around templating. I already have my templating pattern figured out and would just like an array of error fields in the style of vuelidate (ie data only) for a11y purposes.

**Comment by scniro** [comment]
Any update on pulling all the errors? I'm wanting to show a list of the total form errors in a modal before proceeding per my use case. I was stoked to find this lib, worked it all in, and am now scratching my head at the finish line as to why I can't find a list of my offending errors. This seems fundamental and I'm thinking I need to ditch this 😭

**Comment by dobromir-hristov** [comment]
You can use the error extractor as just a data provider to extract the error for a certain field for you. Adding a generic method is not as easy as we have to add ability to pass error messages, attribute extraction, nested validation rule extraction and so on, which is already added to the vuelidate-error-extractor library.

You can use it's mixin and add it into your generic form field wrappers to just provide the needed validation data, how you template it is up to you.

**Comment by lextas** [comment]
I was also looking for a way to create some sort of 'validation summary' since the plugin does not provide support for this I created a plugin myself. For now it is focused on extracting all (invalid) validations and provides support for error message (and overriding). Of course it all depends on your own needs if it's useful. Maybe it gives others a push in the right direction. Adjust to your own needs.

 [VuelidateSummary](https://github.com/lextas/vuelidate-summary)

**Comment by dobromir-hristov** [comment]
https://dobromir-hristov.github.io/vuelidate-error-extractor/multi_error_extractor.html#usage :)

**Comment by lextas** [comment]
> https://dobromir-hristov.github.io/vuelidate-error-extractor/multi_error_extractor.html#usage :)

I needed something where I could just pass an validation result and get an array of invalid properties. Without binding things to a view. For example: in my case I validate incoming requests against a validation scheme and log the validation summary to analyse why some incoming requests fail. Because it has potential for more and is loosely coupled from the view part I decided to share it.

As I said. It depends on everybody's needs if the error extractor fulfills the job. If not; maybe someone can use the snippet to build it's own. If you still think it doesn't belong here: let me know; then I'll remove my comments. :)

**Comment by dobromir-hristov** [comment]
Hmm I see what you mean. Was planning to extract the logic for extracting  errors without templates, but its generally just used for viewing, so its still "pending".

**Comment by douglasg14b** [comment]
Was looking at form validation libs, and extracting a list of errors is a must have for accessibility.

**Comment by thedamon** [comment]
MultiErrorExtractor seems quite cool, but kinda opposite in philosophy to vuelidate (which deals exclusively in data, rather than in the template area), so I think while it's nice that it can provide a list of errors itself, I'm not convinced it 'solves' this issue.

I think it's logical to want/expect vuelidate itself to be able to surface an array of failing validations on its own. Surfacing that already existing behaviour as a separate function import from multi-error-extractor would be handy, too!

**Comment by dobromir-hristov** [comment]
I get what you mean. I have plans to extract those helpers, just been super busy lately.
