### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by parthibd** [vuelidate/vuelidate#439]
Is vuelidate dead ?

**Comment by phox081** [comment]
in this comment: https://github.com/monterail/vuelidate/issues/423#issuecomment-459982683
said: 

> See this comment [#369 (comment)](https://github.com/monterail/vuelidate/issues/369#issuecomment-445225102)

> Hi,
The project is hopefully still alive, but things have changed recently indeed. I am no longer able to maintain it due to the fact that I left the company i was developing it under and I no longer have the commit rights. It is supposed to be maintained by monterail, so hopefully you will see more activity from their side soon.

that issue has been closed reporting:
"Choose which validation framework to use"
https://github.com/cylc/cylc-web/issues/13

**Comment by manniL** [comment]
As the company which owns the GH repo is still active, I tweeted them :relaxed: 

https://twitter.com/TheAlexLichter/status/1100523738020352002

Feel free to RT or so :man_shrugging: Maybe that helps!

**Comment by shentao** [comment]
One of the original creators here in the same situation as @Frizi.
I think forking it might be a good call.

I was also thinking about building a new vuelidate-like library that would get rid of some of the APIs (like `$each`) which encourage bad component design and are also the reason that makes the library unnecessarily complicated. Should make it simpler and easier to maintain.

Sadly, I can’t give an ETA, since I’m still way behind on the new vue-multiselect release.

But if someone would like to join and help – let me know!

**Comment by robcresswell** [comment]
Given Monterails rather blunt avoidance of the question here https://twitter.com/monterail/status/1100685357308395521 maybe forking is the way to go...

**Comment by korzeniowski** [comment]
Hello everyone, Head of FE at Monterail here. We are currently in talks regarding handing over Vuelidate to new maintainers (@shentao, @NataliaTepluhina, @dobromir-hristov and @bencodezen) and moving the repo to an independent Github org. Sorry for the lack of updates and possible confusion regarding the aforementioned tweets. We will make sure the library gets maintained and provide any necessary support to the new maintainers. We'll let you know as soon as we have next steps defined.

**Comment by robcresswell** [comment]
Amazing, thanks @korzeniowski

**Comment by manniL** [comment]
I think we can close that issue now with a huge **No, it's not! 🙌 🎉** 
😋

**Comment by parthibd** [comment]
No, it's not dead 🎉🎉🎉🎉🎉😊😊

**Comment by nolde** [comment]
Should this be reopened?

It has been almost 4 months since it was announced that it would handed over to someone else, and there is still no movement at all in the repo.

Did something go wrong? 

@korzeniowski @shentao, @NataliaTepluhina, @dobromir-hristov @bencodezen

**Comment by shentao** [comment]
Hey @nolde. Thank you for your concern. I have to sadly say, we slightly overestimated our capacity to introduce changes, but we did make some progress. It’s just not as visible and meaningful as we wished it would be. 😓 Sorry for that.

We just published a roadmap for the project which we will also be used as a status update page.
See: #494

**Comment by nolde** [comment]
Thanks for the quick answer, @shentao !

The roadmap looks good, but do you have any target dates? I know that your guys have been fixing a few issues (e.g. #454, which has been fixed 2 month ago), but no releases have been done. Wouldn't it be worthwhile to release patch changes as soon as you have a few bugfixes in?

Sorry for adding more pressure. My company do rely on vuelidate a whole lot, and we would like to avoid needlessly forking it or creating temporary fixes.

**Comment by hellboy81** [comment]
This project is dead. One week lost and it does not work. Use `vee-validate` instead.

**Comment by dobromir-hristov** [comment]
Project is not dead, and it does in fact work. If `vee-validate` works for your needs, then you are very much free to use it.
If the project is dead, you will see a public note about it. Locking this thread.
