### ISSUE TITLE
Required field is initially false - cant change with $touch()

### ISSUE THREAD

**Issue by fasterlars** [vuelidate/vuelidate#648]
I have a custom text input component which takes props to show the text, and amongst others a required validator. Now I would like to show that the field is required from the start, not when the user first types types something. 

I can see from the docs that I should call $touch() on the property, but it doesent seem to trigger the required field. Which by the way doesent make sense to me, because why is the required validator initially false when it is in fact true? 

Please refer to this fiddle: https://jsfiddle.net/Le5dsgxj/3/

Thanks :)

**Comment by shentao** [comment]
Hey! If you remove the `minLength` validator you will notice that the `required` validator works properly. This might not be obvious (sorry for that), but generally if in the validator’s status says `false` it means it’s failing. So it works just as you would expect, just in reverse.

See example:
https://jsfiddle.net/shentao/2go8vq5t/

**Comment by fasterlars** [comment]
Thanks for your answer.
Well I actually also need the minLenght (and other validators).. 
Regarding the jsfiddle you linked, I can only see that you negated the `v-if="!$v.text.required" ` condition - which is why the required text shows. The real required property is still false? Am I missing something?

**Comment by shentao** [comment]
I only removed the `minLength` to showcase that the `required` validator works properly. You can add it back along with other validators.
Please read the docs:
https://vuelidate.js.org/#sub-v-values
> $invalid | boolean | Indicates the state of validation for given model. becomes true when any of it's child validators specified in options returns a falsy value. In case of validation groups, all grouped validators are considered.

Which means, if any of the validators return `false` it means they are failing. If they return `true`, it means they are passing.

I think, what might be confusing here is that `minLength` returns true when the length is `0`. It might sound counter-intuitive, but is actually something we did by design. This is to solve cases where a field is NOT required but if the user decides to pass some data, there are some requirements for the length of it. So if `minLength` was to return `false` (NOT passing) it would show an error even if the field was not filled. 

In other words `minLength` checks for the length if the field is actually filled. Which means is NOT EMPTY. And `required` is the validator that checks for emptiness.

So if we modify your example again: https://jsfiddle.net/shentao/mxq4Lcg9/1/ and only leave the `minLength` validator, you will see that the field is `valid` (returning `true`) when it’s empty, but if you start typing, it will let you know that the field has to be at least 5 characters long. But the field is not required.

Another example of this behaviour would be the `email` validator. Imagine you have an email field that is NOT required. You don’t want to show an error when it’s empty right? But if the user decides to type something, you want to make sure that it is an email that the user inputs. 

To sum up. Most validators (`minLength`, `email` etc.) ignore empty values, whereas `required` specifically checks against empty values.

I hope this helps. Let me know if you have any other questions!

**Comment by fasterlars** [comment]
Alright, I understand what you are saying, and it makes sense.

What I need is to display an input field with required and minLength validations. To tell the user that this field is required, I would like to put a * besides the input field, so the user doesent have to click the submit button to know which fields are required. A pretty basic scenario :)

So in order to show this * dynamically, instead of looking at the required propery, I should instead see if an `$params.required` object exists? Or what is the correct way to achieve this?
Thanks!

**Comment by shentao** [comment]
That is correct! I would also remove the `$touch()` in `created()`, since you’re already using `$model` in your `v-model` which will automatically change the `$dirty` status once the user starts typing.
Modified your example: https://jsfiddle.net/shentao/0au8z9xf/
