### ISSUE TITLE
Unable to validate array in vuelidate 2.0.0-alpha.0

### ISSUE THREAD

**Issue by hasnen206** [vuelidate/vuelidate#676]
Hi, I am trying to understand vue composition api and using vuelidate 2.0 plugin to do some validations around by forms.
I have an array of objects and would like to validate it but I do not see any support for $each like its previous version.

I am referring to examples provided by @shentao https://github.com/shentao/fvlidate but do not see any that could help me on my endeavor.

I would really appreciate it if you could help and share some code on how to validate arrays with v2.0.

Lastly, thank you for creating such an awesome plugin.

**Comment by shentao** [comment]
Hey @hasnen206! 
I guess it would come to this (cc @dobromir-hristov) one day... Soo... Validating arrays with `$each` was extremely problematic in the current version of Vuelidate. It has lead to multiple memory leaks and generally wierd issues. 

We decided to remove support for it. 

We are now working on a way to fill in this hole. So far we have one recommendation:
- Creating child components with their own validation rules for each element. Those should then automatically be collected by the parent component. Just make sure to use a unique key to register those child components.

- We also started working on some helpers: `every` and `some` that can be applied to arrays itself. Similarly to `<Array>.every` and `<Array>.some` it would take a validation object (same structure as with `$each`) and run it against the whole array and then get you a result for the whole array depending if all or at least 1 element has passed the validation. This is not yet implemented, though we might have a draft of it somewhere.

If you could provide us with a nicely described use case, we could try to build a suitable solution for it.

**Comment by hasnen206** [comment]
Thanks for the quick reply @shentao 
I can take the child component approach in my scenario.
That will work for me.

Thanks again.

**Comment by DanielAsher** [comment]
It's hard to blame an alpha.0 release, but I have just spent the best part of a day tracking down this issue. Debugging the exception throw in Vue 3 was a trial:
```
Uncaught (in promise) TypeError: Cannot read property '0' of undefined
    at eval (eval at compileToFunction (vue.esm-browser.js:12523), <anonymous>:691:54)
    at renderList (vue.esm-browser.js:7135)
    at Proxy.render (eval at compileToFunction (vue.esm-browser.js:12523), <anonymous>:683:68)
    at renderComponentRoot (vue.esm-browser.js:1595)
    at componentEffect (vue.esm-browser.js:5223)
    at reactiveEffect (vue.esm-browser.js:388)
    at callWithErrorHandling (vue.esm-browser.js:1271)
    at flushJobs (vue.esm-browser.js:1424)
```

it was the result of migrating Vue 2/Vuelidate code to Vue 3. The exception was throw as a result of the Vue compiled code:
```
                    return (_openBlock(), _createBlock(_component_songmodel_section, {
                      id: `song-section-${index + 1}`,
                      index: index,
                      layoutStyle: sectionLayoutStyle,
                      key: index,
                      msStartBeatOffset: song.msStartBeatOffset,
                      ref: `song-section-${index}`,
                      section: $v.song.sections.$each[index],
                      isSectionLinked: isSectionLinked(index),
                     ...
```
deep inside a virtual file called `debugger:///VM48662`

Obviously I set myself up for a fall, but it would have been great to have a note on breaking changes on the `next` branch `README.md`

**Comment by IlCallo** [comment]
@shentao 
I've an interesting use case which cannot be covered by the existing features of v2.
I'll write it here as it seemed the most fitting issue, even if closed, but I can copy/paste it to a new issue.

I'm using Quasar QTable to display my data, and Vuelidate 2 with Composition API to validate it.
The data require a row-level validation (aka, every single element of the array, as `$each` did) because some fields are required only when some others are set.
Since I'm using the dynamic [`body-cell-[name]` named slots](https://quasar.dev/vue-components/table#Body-slots), I'm unable to wrap the row level validation into a component to leverage the nested component validation.
This is due to the fact that I'm just providing named slot contents into the table, so I don't have an element I could use as root for the child component.

```html
<q-table :data="v.books.$model" :columns="columns">
    <template #body-cell-author="props">
      <q-td :props="props">
        {{ props.value }}

        <q-popup-edit v-model="props.row.author" auto-save>
          <q-input v-model="props.row.author" />
        </q-popup-edit>
      </q-td>
    </template>

    <template #body-cell-title="props">
      <q-td :props="props">
        {{ props.value }}

        <q-popup-edit v-model="props.row.title" auto-save>
          <q-input v-model="props.row.title" />
        </q-popup-edit>
      </q-td>
    </template>

    <template #body-cell-isbn="props">
      <q-td :props="props">
        {{ props.value }}

        <q-popup-edit v-model="props.row.isbn" auto-save>
          <q-input v-model="props.row.isbn" />
        </q-popup-edit>
      </q-td>
    </template>
</q-table>
```

The workaround for my scenario is to abandon the cleaner dynamic slots to enter a `v-if` hell, using the `body` slot instead, where I can create a new Vue component extending a `<q-tr>`, and adding there the validation.
But the workaround will force me to create an unnecessary component, make the code less readable and more verbose, while I really just need some simple validation on the model.

Another pain point is that Vue, like all other modern frameworks, currently push forward the idea that the View should be the reflection of the Controller model changes. While with Vue SFC is harder to distinguish what is Controller and what is View, relying on the Vue components parent-child relation to determine the model status seems to be against that assumption to me. If not technichally (as Vue just compiler everything to render functions), at least logically
