### ISSUE TITLE
Numeric validator fails with decimals and floats

### ISSUE THREAD

**Issue by moksamedia** [vuelidate/vuelidate#706]
Seems like "numeric" ought to be renamed "integer" since the regex being used for it only passes integers and decimals are just as numeric as integers. Or the numeric validator regex should be updated to include decimals, float, etc...

Thanks,

Andrew

**Comment by dobromir-hristov** [comment]
Yeah, you are correct, its integers, not numbers. This is a breaking change though, @shentao what do you think? Rename it to integer and add a proper numeric validator?

```js
export function isNumeric(num){
  return !isNaN(num)
}
```

**Comment by shentao** [comment]
Yup! I think we should do that, just making sure the new numeric validator is fully backward compatible (just a bit broader). @mokkabonna would you like to contribute that to the `next` branch?

**Comment by mokkabonna** [comment]
I guess you mean @moksamedia

**Comment by shentao** [comment]
Whoopsie! Yes, @moksamedia. No idea why GitHub suggested you, super sorry!

**Comment by mokkabonna** [comment]
However incidentally I might have something to say anyway:

I had a suggestion on another validation library: https://github.com/Knockout-Contrib/Knockout-Validation/issues/326

That for a "model based" validation library, I find it a bit weird that what is checked is not the actual model (like typeof num === 'number' and Number.isInteger(123)) but rather that the value is a string that **can** be parsed as a number. It might in some cases behave the same due to implicit casting, but say for an api that uses say JSON schema for validation will fail if the type is string when expecting number. Or even client side with a library like mine: https://github.com/mokkabonna/vue-vuelidate-jsonschema (that one does roll all of the validators with much more strict checking)

Or say, you have some code like this that run after validation is true for some integer. 

```
if (!this.$vm.myinteger.$invalid) {
  this.myinteger + 5
}
```

If mynumber is the string "123", the result will be the string "1235", not the number 128. Easy that bugs arise from that, since you have the impression that you are dealing with a valid number.

As mentioned on the other library: I think it is better if the validation is strict and rather make use of built in helpers like `<input v-model.number="age" type="number">` to help you parse strings to integer.

Just wanted to throw that out there.

Also some extra remarks:

1. You already have a integer validator
https://github.com/vuelidate/vuelidate/blob/master/src/validators/integer.js

2. That validator does not support more advanced formats like `1.2e1`

3. You have a decimal validator
https://github.com/vuelidate/vuelidate/blob/master/src/validators/decimal.js

**Comment by dobromir-hristov** [comment]
closed in #711

**Comment by deni5n** [comment]
it might be better to use _^\d*([.,]\d+)?$_  this will allow for dot and comma handling

**Comment by NikosMetaxakis** [comment]
Hi everyone,

numeric validation fails on a float number


(snippet from vue developer tools $v object)
itemFinalCost:Object
$anyDirty:true
$anyError:true
$dirty:true
$error:true
$invalid:true
**$model:298.84**
$params:Object
numeric:Object
type:"numeric"
$pending:false
**numeric:false**


value gets process with those methods:

`
calculateWOVatCost(itemFinalCost) {
      this.setValues(itemFinalCost, 'itemFinalCost');
      if(!this.$v.values.vatPercent.$invalid && !this.$v.values.quantity.$invalid) {
        const vat      = this.values.vatPercent;
        const quantity = this.values.quantity;
        //unitPriceWOVat calculation
        const uWOVat   = itemFinalCost / (quantity * (vat / 100 + 1));
        this.setValues(uWOVat, 'unitPriceWOVat');
        //vatCost calculation
        this.calculateVatCost(uWOVat);
      }
    },
`

`
setValues(value, property) {
      if(property !== 'description' && property !== 'measurementUnit' && parseFloat(value)) {
        value                 = parseFloat(value).toFixed(2);
        this.values[property] = parseFloat(value);
      } else {
        this.values[property] = value;
      }
      //Set property to 'touched'
      this.$v.values[property].$touch();
      //Emit values to parent component
      this.$emit('valuesSet', this.values, this.frontId);
    },
`

`vatSet(vat) {
      this.setValues(vat, 'vatPercent');
      console.log('$v.final.invalid: ', this.$v.values.itemFinalCost.$invalid, ' this.final: ', this.values.itemFinalCost);
      if(!this.$v.values.unitPriceWOVat.$invalid && this.values.unitPriceWOVat > 0) {
        console.log('vatSet calling calcFinal');
        this.calculateFinalCost(this.values.unitPriceWOVat);
      } else if(!this.$v.values.itemFinalCost.$invalid && this.values.itemFinalCost > 0) {
        console.log('vatSet calling calcWOVat');
        this.calculateWOVatCost(this.values.itemFinalCost);
      }
    },`
  
  validations object snippet,  
`validations: {
   values: {
{{several items in here, the last item in the object is the following}}
itemFinalCost  : {
        required,
        numeric,
      },
  }
}`
    
    in run to the case where , 
    itemFinalCost has already been set 
    (but because nothing else has been set in the form essentially only setValues() has been called)
    
    then vatSet is called by an @change event and the
  `}  else if(!this.$v.values.itemFinalCost.$invalid && this.values.itemFinalCost > 0)`
fails because !this.$v.values.itemFinalCost.$invalid returns false !!!

the value is a float in the model,

subsequent tests showed under no circumstance the numeric check passes, on other numeric values
that had similar treatment the check is passing!!!
