### ISSUE TITLE
useVuelidate doesn't update errors, dirty, validate state

### ISSUE THREAD

**Issue by devKid88** [vuelidate/vuelidate#709]
Checked on https://vuelidate-next.netlify.app/advanced_usage.html#composition-api and based on it I created the example bellow
### Please use the following jsfiddle to provide a reproduction of your problem

Not sure how to add the next version on fiddle, but I will paste code here so you can check.

```<template>
  <div class="login-container">
    <div class="login-form">
          <form @submit.prevent="handleLogin">
            <div class="field">
              <input v-model="username" placeholder="username" :class="{ 'invalid': v.username.$error }" />
              <small v-if="v.username.$error" class="invalid">Username is not available.</small>
            </div>
            <div class="field">
              <input v-model="password" type="password" placeholder="password" />
            </div>
            <div class="field">
              <button class="button-primary" type="submit" label="login" />
            </div>
          </form>

          <p v-for="(error, index) of v.$errors" :key="index">
            {{ error }}
          </p>

          <pre>{{ v }}</pre>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from "vue";
// @ts-ignore
import { useVuelidate } from "@vuelidate/core";
// @ts-ignore
import { email, required } from "@vuelidate/validators";
import { useAuth } from "@/hooks/useAuth";

export default defineComponent({
  name: "Login",
  setup() {
    const { login } = useAuth();
    const username = ref("");
    const password = ref("");

    const rules = {
      username: { required, email },
      password: { required },
    };

    const v = useVuelidate(rules, { username, password });

    const handleLogin = () => login(username.value, password.value);

    return {
      username,
      password,
      handleLogin,
      v,
    };
  },
});
</script>
```

Whatever I change only the model is updated, nothing about form related props ( dirty, errors, etc ).
I perform several blur/focus out in each of the input, just to check if it will trigger change inside v, but nothing.
Am I doing something wrong, or this has some bug?

For example check image bellow

![image](https://user-images.githubusercontent.com/20492089/95027498-3db58000-0699-11eb-98d5-2bbb1d55dd33.png)

**Comment by aethr** [comment]
Vuelidate 2 currently uses lazy validation, which means none of the validators will run until the field's validation is marked `$dirty: true`. This may be re-worked after the discussion in #707 , but for now you have to manually tell Vuelidate when a field is updated.

There are a few ways to do this:
- in the `v-model` of your input, bind `v.username.$model` instead of `username` - this is a proxy for your normal data that marks the field as dirty on change
- set up each validation with `$autoDirty: true` and Vuelidate will set up a watcher on the data property
- add `@input="v.username.$touch"` to your input to manually mark the field as dirty when it changes. this would also allow you to force the validation to trigger on `blur` events even if the user hasn't changed the value.

Hope that helps!

**Comment by devKid88** [comment]
@aethr Thanks for the info, I saw that #707 but thought maybe this is a separated scenario. 
Yes, it was helpful, I will close the issue.

**Comment by shentao** [comment]
Thanks, @aethr for jumping in! Really appreciate the recent contributions!

**Comment by Uraharadono** [comment]
Since I came here from google top results, and even tho answers proved to be helpful, it took me some time to visualize and figure out changes. `$autoDirty: true` does not go into `setup: () => ({ v$: useVuelidate() }), `it goes into every single validation you have like so 
```
setup: () => ({ v$: useVuelidate() }),
data() {
	return {
		username: '',
		password: '',
	};
},
validations() {
	return {
		username: {
			required,
			email,
			minLength: minLength(6),
			$autoDirty: true,
		},
		password: {
			required,
			minLength: minLength(8),
			$autoDirty: true,
		},
	};
},
```

If you want to have a custom message for each and every validation rule you have set, you have to go as follows:

```
<input
	v-model.trim="username"
	type="username"
	class="form-control"
	placeholder="Email address"
/>
<div v-if="v$.username.required.$invalid && v$.username.$dirty" class="text-danger">
	Field is required
</div>
<div v-if="v$.username.email.$invalid && v$.username.$dirty" class="text-danger">
	Field has to be email
</div>
```
				
				
or 

```
<div v-if="v$.password.$dirty">
	<div v-if="v$.password.required.$invalid" class="text-danger">Field is required</div>
	<div v-if="v$.password.minLength.$invalid" class="text-danger">
		Passwords in our system are a bit longer than that
	</div>
</div>
```


This was like so in vue 2:                 `v-if="!$v.username.required && $v.username.$dirty"`

**Comment by aethr** [comment]
@Uraharadono there is probably a simpler way to configure your validators with custom messages, documented here: https://vuelidate-next.netlify.app/custom_validators.html#custom-error-messages

Once the validators themselves are configured with the messages you want, it should be enough to check whether a validation rule has any values in the `$errors` property. `$errors` should contain a list of error messages **only when the field is dirty**. Then you can do something like:
```js
              <div v-for="error in $v.username.$errors" :key="error" class="text-danger">{{ error.$message }}</p>
```
