### ISSUE TITLE
email validation accepts lower-case domain and TLD only

### ISSUE THREAD

**Issue by c-myers1** [vuelidate/vuelidate#747]
Is it by design that vuelidate accepts MYNAME@mail.com as valid but not MYNAME@MAIL.COM?

If not, then I think there is a bug. A user might have caps lock on and an error should not flag for this.

**Comment by aethr** [comment]
Disclaimer: I'm not a Vuelidate maintainer so this is just my opinion.

All DNS names (so the part of the email after the @) are case insensitive, while the local part (before the @) can be case sensitive depending on the email system.

For this reason I think it's sensible to convert the domain portion of an email address to lowercase even if the user enters it as UPPERCASE or Mixed Case.

I'm not sure if this is intentional in Vuelidate, but I think it helps to protect you against a few issues:
- you want to prevent duplicate email entries for "myname@example.com" and "myname@EXAMPLE.COM" - these are the same address
- you may want to allow "MyName@example.com" and "myname@example.com" as *separate* entries because you don't know whether the example.com email provider is case-sensitive or not

While you may choose to display to the user what they entered un-modified, I would recommend converting the domain to lowercase before validation and before storage.

**Comment by c-myers1** [comment]
makes sense

**Comment by Jaimies** [comment]
Can we close the issue?

**Comment by malinushj** [comment]
For those looking for an intermediary fix, here's my solution using a helper function:

```js
// force the domain of the email to be lowercase and send it to the email validator
export const emailFormatter = (value) => {
  if (!value) return value;
  let parts = value.split('@');
  parts[1] = parts[1].toLowerCase();
  return parts.join('@');
}
```

This is how it would be used:
```js
import { email, required } from 'vuelidate/lib/validators';
import { emailFormatter } from ...

// ...
validations: {
    form: {
      email: {
        required,
        email: (val) => email(emailFormatter(val)),
      },
    },
  },
// ...
```

**Comment by ricky11** [comment]
how would you force  everthing to be lowercase in the validations?
