### ISSUE TITLE
Cannot create custom validator based on another field value

### ISSUE THREAD

**Issue by syphzur** [vuelidate/vuelidate#749]
Is there any way to create custom validator based on another field value with Vuelidate 2 and composition api? 
Tried to follow examples described in 'Accessing component' on https://vuelidate-next.netlify.app/ but it doesn't work for me.

First example: 
![image](https://user-images.githubusercontent.com/32513657/98481348-e48dbe80-21f9-11eb-9d14-86f5d87aed3c.png)
'this' is undefined so I cannot access second field value

Second example using arrow function and 'parentVm' argument:
![image](https://user-images.githubusercontent.com/32513657/98481500-ec9a2e00-21fa-11eb-92bd-691ddbd5351d.png)
'vm' is always undefined and has to be optional to avoid type error: 
           _Type '(value: any, vm: any) => boolean' is not assignable to type 'ValidationRuleWithoutParams<unknown> | ValidationArgs | ValidationRuleWithParams<any, unknown> | ValidatorFn<unknown>'._

Dependencies:
    "@vue/composition-api": "^1.0.0-beta.19",
    "@vuelidate/core": "^2.0.0-alpha.7",
    "@vuelidate/validators": "^2.0.0-alpha.5",
    "vue": "^2.6.11",

**Comment by aethr** [comment]
Since you're using the composition API, it's reasonable to expect the values that you're validating are actually available in the scope of the setup function where your rules are defined.

```js
  setup() {
    const name = ref('');
    const limit = ref(20);
    const rules = {
      name: {
        maxLength: (val) => val.length <= unref(limit), // `limit` is already available here, and is reactive
      },
    },
   
    const v = useVuelidate({ name }, rules);
  },
```

Generally nothing in `setup` is going to have access to `this` or the vm, since it isn't ready yet. Does that help answer your question?

**Comment by shentao** [comment]
The answer provided by @aethr should be enough. Closing :)

**Comment by syphzur** [comment]
It works, thanks!

**Comment by khorsky** [comment]
Hi, I'd like to reopen this issue, because I've encountered the same problem.

Solution proposed by @aethr works only when I define my rules inside setup function.

When I want to export my rules to a module (because I want to share the rules across multiple components), I cannot use this solution. I would need to use `vm` to access another fields - but it's undefined.
