### ISSUE TITLE
parentVm is undefined

### ISSUE THREAD

**Issue by zadorozhny** [vuelidate/vuelidate#775]
"@vuelidate/core": "^2.0.0-alpha.8",
"@vuelidate/validators": "^2.0.0-alpha.5",

withParams(params: Params, rule: CustomRule | ValidationRule)

CustomRule = (value: any, parentVm?: any)

CustomRule doesn't receive the second parameter parentVm

**Comment by fisheyemh** [comment]
Hi,
i'm having this issue too.

**Comment by dobromir-hristov** [comment]
As of now, validators do not have access to the parentVM as a second parameter. https://github.com/vuelidate/vuelidate/blob/next/packages/vuelidate/src/core.js#L69-L72

**Comment by bisubus** [comment]
@dobromir-hristov Is this intentional? This seems to be a design problem because this requires to define validators in a scope where a state is available while they were originally reusable independent helpers. When upgrading to 2, my `setup` was immediately flooded with validation rule factories. Also this renders built-ins like requiredIf and sameAs useless, while they clearly have their uses.

**Comment by dobromir-hristov** [comment]
Its more of an oversight/implementation complication for now. I think we could add it in the future though. You could use `getCurrentInstance` inside the validator for now.

The `requiredIf` validator accepts the field value you want to validate against as a parameter.

```js
required: requiredIf(ref1)
```
