### ISSUE TITLE
Question. Can the useVuelidate function be called outside a component?

### ISSUE THREAD

**Issue by wyepez** [vuelidate/vuelidate#815]
I just wanted to use a global $v model across the entire app and when I try to call the useVuelidate function in a module I got the following error: Uncaught TypeError: Cannot read property 'type' of null. It seems like I can only call useVuelidate inside a context of a Vue component.

**Comment by dobromir-hristov** [comment]
Correct.

**Comment by wyepez** [comment]
Ok. Just for curiosity, is there any reason why a $v model is coupled to a component?

**Comment by dobromir-hristov** [comment]
Because we cannot call getCurrentInstance or provide inject, outside of Vue Components.

You can have a component that setups Vuelidate and save the Vuelidate instance anywhere you want, vuex or whatever.

**Comment by shentao** [comment]
But that’s an interesting idea to consider. I don’t think Vuelidate should be coupled to a component. What about we add a flag that makes it work outside of a component context?

**Comment by miralize** [comment]
Correct me if I'm wrong & I'm understanding that you're bound vue's underlying mechanisms, but this hard rule prevents doing what the composition api was supposed to be for. 

In an ideal world I could extract all my form's logic (state, forms, submission) to a single file for re-use or to minimize the business logic within an extra large component thats difficult to break up otherwise. 

Or perhaps I want to wrap useVuelidate & add a series of helpers to be able to work with another third-party library.

**Comment by dobromir-hristov** [comment]
You still can do that, it's just that it has to be called in a sync way.

Because we use getCurrentInstance for a few things, we rely on it.

Calling it async in setup will throw those errors.

I think we can allow passing it as a config, so users can still use it async.

https://v3.vuejs.org/api/composition-api.html#getcurrentinstance
