### ISSUE TITLE
Release Plans?

### ISSUE THREAD

**Issue by shawnwildermuth** [vuelidate/vuelidate#829]
I've included Vuelidate 2 in a Pluralsight course and am trying to plan on updating based on the release. Any roadmap for release?

**Comment by shentao** [comment]
Hey! I think we are pretty close to a beta release. cc @dobromir-hristov

**Comment by dobromir-hristov** [comment]
Yeah, API should be stable

**Comment by shawnwildermuth** [comment]
Thanks for the info!

**Comment by stevebering** [comment]
I am looking for an update on the release plan. This issue is 6 months old but we still haven't moved from producing alpha releases. When is a beta or 2.0 release planning to be released? We are working on a new Vue 3 project and wondering if we should have concerns since the current version is still an alpha build. Is there a roadmap for 2.0?

**Comment by dobromir-hristov** [comment]
Hey there. Well, we havent really changed the API months now, mostly fixes and feature updates. I am mostly maintaining the library alone these days, so things are a bit slower, and my actual job isnt getting any easier 🤣 

I have one more feature in mind - #897 and then will probably do a release candidate :)
