### ISSUE TITLE
Async validators display errors when still resolving promise

### ISSUE THREAD

**Issue by rjd22** [vuelidate/vuelidate#875]
**Describe the bug**
Async validators seem to display errors when the promise is still resolving.

**Reproduction URL**
https://codesandbox.io/s/vuelidate-requiredif-issue-forked-xe5ef?file=/src/App.vue

**To Reproduce**
1. Type some text in the box
2. See that the `asyncTest` error is shown when resolving the promise
3. See that when the `asyncTest` promise is resolved the error is hidden

**Expected behavior**
I would expect while resolving the promise not error to be shown until the Promise returns a false. Sometimes something needs to be validated in the backend and can some time to respond resulting in misleading customers.

**Comment by MinatoHikari** [comment]
```javascript
asyncTest: helpers.withMessage(
    ({ $pending }) => {
        if (!params.$pending) return 'testErr';
        return '';
    },
    helpers.withAsync(async (value) => {
          await new Promise((r) => setTimeout(r, 5000));
          return true;
    })
),
```

**Comment by dobromir-hristov** [comment]
Yeah, that is an option. You could check whether the thing is still pending. 

Maybe we should do that internally, but not sure about the overall user exp.. that will cause forms to flash, from red to nothing to red again, potentially.

**Comment by rjd22** [comment]
@dobromir-hristov atm. I actually check if it's pending to solve this problem. 

But having errors shown when it's not sure if there is even going to be an error is kind of weird developer experience if you ask me.

**Comment by dobromir-hristov** [comment]
Hey, sorry for the wait, looking at this again.

Linked a Draft PR showing the change, let me know what you think :)

**Comment by rjd22** [comment]
@dobromir-hristov thank you for taking the time to solve this. Do I understand correctly that `$error` will behave the same and that we have an extra `$invalid` field to check if for async validators that will return `false` when pending and `true` when the async validator resolves an error.

In that case I would say it looks great :+1:

**Comment by dobromir-hristov** [comment]
We always had $invalid, it just used to be false, while the validator was resolving.

I changed that in the PR to keep it false, so no error messages are shown, but the field itself is considered errored, so we don't accidentally submit a form, while it's validating.

**Comment by adamreisnz** [comment]
So is the recommendation to use `$invalid` instead of `$error` to mark a field as invalid/having an error?
It currently flashes invalid while the async validator is running, presumably because we use `$error` to check

The thing is that the [official guide](https://vuelidate-next.netlify.app/guide.html#checking-for-validation-state) recommends to use `$error`, which then causes this problem:
![image](https://github.com/user-attachments/assets/72f2558f-859d-4592-b5d0-6284d7c72a06)

Although the detailed API docs seem to contradict this again, by implying that `$error` should not resolve to `true` while a validator is `$pending`:

![image](https://github.com/user-attachments/assets/a84c4392-c33b-4d11-80d3-ec46a24b76cc)

Honestly, I think something is not working quite as expected. I can see the `$error` flag quickly toggling to `true` and then back to `false` the moment the async validator completes its check (despite passing validation), but I will raise this as a new issue.

**Comment by bettysteger** [comment]
> Honestly, I think something is not working quite as expected. I can see the `$error` flag quickly toggling to `true` and then back to `false` the moment the async validator completes its check (despite passing validation), but I will raise this as a new issue.

@adamreisnz i have the same problem, have you found a solution?

**Comment by adamreisnz** [comment]
@bettysteger I am not sure, it was a while ago. I checked the codebase in the relevant file, and I think we still explicitly check both flags like so:

```
:has-error="$v.name.$error && !$v.name.$pending"
```

And upon confirmation we check `$invalid` and `$pending`:

```
const confirm = () => {
  if (!$v.value.$invalid && !$v.value.$pending) {
    emit('confirm', model.value)
  }
}
```
