### ISSUE TITLE
email should have the option to allow for predefined content

### ISSUE THREAD

**Issue by cmkozak** [vuelidate/vuelidate#910]
There are situations where we use the email validator for creating mailto links. mailto links allow you to add predefined content to the link itself (subject, bcc, cc, and body). Some examples:

`mailto:someone@yoursite.com?subject=Mail from Our Site`
`mailto:someone@yoursite.com?subject=Mail from Our Site&cc=example@test.com`
`mailto:someone@text.com?cc=someoneelse@theirsite.com, another@thatsite.com`

Additional information about mailto predefined content: https://css-tricks.com/snippets/html/mailto-links/

Using the email validator in Vuelidate does not allow for any predefined content.

![image](https://user-images.githubusercontent.com/22403212/127777334-24bcf7c3-01aa-46c6-bd88-5ada77e3c8c5.png)

I understand that we don't want to always allow for predefined content, especially for situations like forms where they need just a user's email. However, having the option to allow for it would be great especially for situations where we're using the validation for mailto links.

**Comment by dobromir-hristov** [comment]
Hi there, 

This looks interesting but I think its a bit out of scope for the email validator. And because it is not exported as a function, there is no way to pass params to it...

You are the first one to request such a thing, so I would call it a niche case.

I would probably create the result you want, by giving the user separate fields for `cc` and `subject`. That way you can properly validate each and just construct the final result.
