### ISSUE TITLE
Cannot find name 'Vue'

### ISSUE THREAD

**Issue by NicolasMelin** [vuelidate/vuelidate#949]
Hello,

I have a problem only when I run this command ```vue-tsc --noEmit``` :

![Capture](https://user-images.githubusercontent.com/13767020/136559281-bf3ae8f5-ff6c-4bd8-80cc-7a9f254be035.PNG)

In fact, 'Vue' is never import/declared in the typescript file.

Can you help me please ?

Thakns by advance.

Best regards

**Comment by dobromir-hristov** [comment]
Could be a regression from a recent contribution.

I will try to fix it later.

**Comment by dobromir-hristov** [comment]
Just use the previous version, we are working on a fix.

**Comment by dobromir-hristov** [comment]
Hey sorry for delaying so long. It should be fixed now.

I am near the end of the features I wanted to implement. Things are looking pretty stable as of now. I am working in the little time I have on the project, but I am giving my best.

Hope to have a beta release, cleanup docs, then rc. Probably in the next month, since winter is coming I will have more "at-home" time.
